version: 2.1
orbs:
  docker: circleci/docker@1.0.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest
        environment:
          NODE_ENV: development
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - store_artifacts:
          path: coverage
workflows:
    build-and-test:
      jobs:
        - build-and-test